-- ============================================================
-- Performance: organization_id indexes, composite indexes,
-- messaging conversation index, and cached RLS org lookup.
--
-- Rationale:
--   - organization_id is the primary RLS filter on every table.
--     Without an index, every RLS check triggers a sequential scan.
--   - Composite indexes cover the most common two-column filter
--     patterns observed in the application query layer.
--   - get_user_org_id() is STABLE + SECURITY DEFINER so Postgres
--     can cache the result within a single statement, eliminating
--     repeated subquery evaluations inside RLS policies.
-- ============================================================


-- ============================================================
-- SECTION 1: organization_id single-column indexes (HIGH priority)
-- Every table that is filtered/scanned by org at the RLS layer
-- must have this index or all multi-tenant queries degrade to
-- sequential scans on the full table.
-- ============================================================

-- activities.organization_id
CREATE INDEX IF NOT EXISTS idx_activities_organization_id
  ON public.activities(organization_id);

-- contacts.organization_id
CREATE INDEX IF NOT EXISTS idx_contacts_organization_id
  ON public.contacts(organization_id);

-- deals.organization_id
CREATE INDEX IF NOT EXISTS idx_deals_organization_id
  ON public.deals(organization_id);

-- leads.organization_id
CREATE INDEX IF NOT EXISTS idx_leads_organization_id
  ON public.leads(organization_id);

-- ai_decisions.organization_id
CREATE INDEX IF NOT EXISTS idx_ai_decisions_organization_id
  ON public.ai_decisions(organization_id);

-- messaging_webhook_events.organization_id
-- Used in webhook dedup checks and audit queries.
CREATE INDEX IF NOT EXISTS idx_messaging_webhook_events_organization_id
  ON public.messaging_webhook_events(organization_id);


-- ============================================================
-- SECTION 2: Composite indexes for common filter patterns
-- These cover the two-column WHERE clauses most frequently
-- generated by the application — verified against the existing
-- query hooks in lib/query/hooks/.
-- ============================================================

-- contacts: filtered by org + stage (funnel/kanban list views)
-- Improves over the existing idx_contacts_stage (single-column)
-- when the RLS org filter is applied alongside.
CREATE INDEX IF NOT EXISTS idx_contacts_org_stage
  ON public.contacts(organization_id, stage);

-- contacts: filtered by org + status (active/inactive toggles)
-- Improves over the existing idx_contacts_status (single-column).
CREATE INDEX IF NOT EXISTS idx_contacts_org_status
  ON public.contacts(organization_id, status);

-- deals: filtered by org + board (pipeline view — most common query)
-- Complements the existing idx_deals_board_id with the org guard.
CREATE INDEX IF NOT EXISTS idx_deals_org_board
  ON public.deals(organization_id, board_id);

-- activities: filtered by org + ordered by date descending
-- Used in activity timelines and deal/contact detail views.
CREATE INDEX IF NOT EXISTS idx_activities_org_date
  ON public.activities(organization_id, date DESC);


-- ============================================================
-- SECTION 3: messaging_conversations status + last_message_at
-- The unified inbox query orders by last_message_at DESC and
-- filters by status (open/closed/pending). Without this index
-- the sort requires a full-table scan on a potentially large
-- table with high write throughput.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_messaging_conversations_status_last_msg
  ON public.messaging_conversations(status, last_message_at DESC);


-- ============================================================
-- SECTION 4: Cached RLS org lookup helper
--
-- get_user_org_id() replaces inline subqueries of the form:
--   (SELECT organization_id FROM profiles WHERE id = auth.uid())
-- inside RLS policies.
--
-- STABLE + SECURITY DEFINER allows Postgres to cache the result
-- for the duration of a single SQL statement, so each multi-row
-- RLS check pays the profile lookup cost only once rather than
-- once per row.
--
-- Restricted to `authenticated` role only — anon and public
-- have no business calling this function.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_user_org_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT organization_id
  FROM public.profiles
  WHERE id = (SELECT auth.uid())
$$;

-- Lock down execution: strip default PUBLIC grant, then grant
-- only to authenticated users.
REVOKE ALL ON FUNCTION public.get_user_org_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_org_id() TO authenticated;

COMMENT ON FUNCTION public.get_user_org_id() IS
  'Returns the organization_id for the currently authenticated user. '
  'STABLE + SECURITY DEFINER enables per-statement result caching inside '
  'RLS policies, eliminating repeated profile lookups.';
